services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - API_KEY=617d78eda2230ec75cfb491afb6917a4
    command: ["npm", "start"]
